### PR TITLE
Fix dependency problems in #263

### PR DESCRIPTION
**Pull request by banacorn**
This is a follow up PR to https://github.com/alanz/lsp/issues/263#issuecomment-764777921.

Stack now builds with `stack-8.8.2.yaml`, `stack-8.8.1.yaml`, `stack-8.6.5.yaml`, `stack-8.6.4.yaml`.

However, I cannot resolve dependency deadlocks in `stack-8.4.4.yaml` and below. 
Should we drop support for `stack-8.4.4.yaml` and below and remove those `.yaml` files?

### CODE REVIEW

**Comment by banacorn** [comment]
I'm marking it "Ready for review" just to trigger the CI.
This is still a work in progress, please don't merge it yet.

**Comment by banacorn** [comment]
> I'm marking it "Ready for review" just to trigger the CI.

Actually I'm not sure if this is necessary anymore, and GitHub action is currently kaput anyway 😄  https://www.githubstatus.com/incidents/tf9v5jjmq2lg

**Comment by banacorn** [comment]
I'm ready to merge!

**Comment by wz1000** [comment]
The stack.yamls look good, could you drop the bounds in the cabal file? https://github.com/alanz/lsp/pull/274 fixes the root cause of the problem in a laxer way.

**Comment by bubba** [comment]
Seems like cabal can build fine on 8.4.4, looking into those weird stack-8.4.4.yaml errors

**Comment by bubba** [comment]
I couldn't push to your branch so I've created another PR with the stack 8.4 fixes in #276

**Comment by alanz** [comment]
> The stack.yamls look good, could you drop the bounds in the cabal file? #274 fixes the root cause of the problem with looser constraints.

Building master with cabal/ghc-8.10.3 still has constraint problems.

**Comment by wz1000** [comment]
What is the error you are getting?

**Comment by alanz** [comment]
I get the same error s #263

**Comment by alanz** [comment]
@wz1000 apologies, the problem *is* gone. I was building it as a dependency of my project, rather than directly.

**Pull request closed without merging**
