### PR TITLE
Update SignatureHelp types

### PR DESCRIPTION
**Pull request by michaelpj**
Now supports `MarkupContent`.

I also added the `activeParameter` field to `SignatureInformation`, which
appears in the spec but not in our implementation.

### CODE REVIEW

**Comment by michaelpj** [comment]
Ah, `activeParameter` was a minor addition in 3.16. Well, this does it too!

**Comment by michaelpj** [comment]
Doh, it needs a support capability too. Let me look at that...

**Comment by michaelpj** [comment]
Oops I did label offset support too :sweat_smile:

**Comment by michaelpj** [comment]
Failure seems spurious.

**Review by jneira — APPROVED** [review]
lgtm

**Comment by jneira** [comment]
rerunning ci

**Pull request merged**
